# DELETE https://typingspeedserver.herokuapp.com/api/scores/2

# GET https://typingspeedserver.herokuapp.com/api/scores


# POST https://typingspeedserver.herokuapp.com/api/scores
# Content-Type: application/json

# {
#     "name": "Matias",
#     "score": 500
# }

POST https://typingspeedserver.herokuapp.com/api/users
Content-Type: application/json

{
    "username": "masa",
    "password": "123"
}